version: '3.6'

services:
  mysql:
    container_name: app-db
    image: mysql:5.7
    volumes:
      - ../backend/replicator/my.cnf:/etc/mysql/my.cnf
      - ../backend/replicator/app-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  audit-db:
    container_name: audit-db
    image: mysql:5.7
    volumes:
      - ../backend/replicator/audit-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "33061:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1    
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    links:
      - zookeeper
    depends_on:
      - zookeeper
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: secure-suite-maxwell:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  maxwell:
    container_name: maxwell
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      HOST: mysql
      USER: maxwell
      PASSWORD: maxwell
      BOOTSTRAP_SERVERS: kafka:9092
      TOPIC: secure-suite-maxwell
      JDBC_OPTIONS: serverTimezone=UTC
    build:
      context: ../backend/replicator/
      dockerfile: maxwell/Dockerfile 
  consumer:
    container_name: consumer
    build: 
      context: ../backend/replicator/consumer
      dockerfile: Dockerfile
    links:
      - audit-db
      - kafka
    depends_on:
      - audit-db
      - maxwell
      - kafka
    environment:
      AUDIT_DB_HOST: audit-db
      AUDIT_DB_PORT: 3306
      AUDIT_DB_USER: maxwell_consumer
      AUDIT_DB_PASSWORD: maxwell_consumer
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: secure-suite-maxwell
  secure-suite-backend:
    container_name: backend
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    build:
      context: ../backend/
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mysql+pymysql://secure_suite:IWANTTOBEHACKED@mysql:3306/secure_suite
      SECRET_KEY: c2VjdXJlLXN1aXRlLWFwcC1kZXYtc2VjcmV0LWtleQ==
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: app.py
      FLASK_ENV: development
  secure-suite-frontend:
    container_name: frontend
    ports:
      - "8080:8080"
    links:
      - secure-suite-backend
    depends_on:
      - secure-suite-backend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    environment:
      BACKEND_URI: http://secure-suite-backend:5000
  
