"""empty message

Revision ID: 5be87b1ac89c
Revises: 
Create Date: 2020-06-21 00:08:01.394880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be87b1ac89c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_key', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_salt', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_key'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_key'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('category',
    sa.Column('category_key', sa.String(length=36), nullable=False),
    sa.Column('ref_user_key', sa.String(length=36), nullable=True),
    sa.Column('category_name', sa.String(length=10), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ref_user_key'], ['user.user_key'], ),
    sa.PrimaryKeyConstraint('category_key'),
    sa.UniqueConstraint('category_key'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('session',
    sa.Column('session_key', sa.String(length=36), nullable=False),
    sa.Column('ref_user_key', sa.String(length=36), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=False),
    sa.Column('time_update', sa.DateTime(), nullable=True),
    sa.Column('locked_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_user_key'], ['user.user_key'], ),
    sa.PrimaryKeyConstraint('session_key'),
    sa.UniqueConstraint('ref_user_key'),
    sa.UniqueConstraint('session_key')
    )
    op.create_table('url',
    sa.Column('url_key', sa.String(length=36), nullable=False),
    sa.Column('ref_user_key', sa.String(length=36), nullable=True),
    sa.Column('url_string', sa.String(length=36), nullable=False),
    sa.Column('url_tokens', sa.Text(), nullable=False),
    sa.Column('url_sequence', sa.Text(), nullable=False),
    sa.Column('url_good', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ref_user_key'], ['user.user_key'], ),
    sa.PrimaryKeyConstraint('url_key'),
    sa.UniqueConstraint('url_key'),
    sa.UniqueConstraint('url_string')
    )
    op.create_table('password',
    sa.Column('password_key', sa.String(length=36), nullable=False),
    sa.Column('ref_user_key', sa.String(length=36), nullable=False),
    sa.Column('ref_category_key', sa.String(length=36), nullable=False),
    sa.Column('password_content', sa.String(length=50), nullable=False),
    sa.Column('password_username', sa.Text(), nullable=False),
    sa.Column('password_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ref_category_key'], ['category.category_key'], ),
    sa.ForeignKeyConstraint(['ref_user_key'], ['user.user_key'], ),
    sa.PrimaryKeyConstraint('password_key'),
    sa.UniqueConstraint('password_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    op.drop_table('url')
    op.drop_table('session')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
