"""empty message

Revision ID: 6f5638384dd9
Revises: efa34375ade1
Create Date: 2020-11-12 22:08:04.254824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f5638384dd9'
down_revision = 'efa34375ade1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'time_update')
    op.drop_column('session', 'time_create')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('time_create', mysql.DATETIME(), nullable=False))
    op.add_column('session', sa.Column('time_update', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
