"""empty message

Revision ID: ed0e97334bc1
Revises: 6f5638384dd9
Create Date: 2020-11-22 18:29:05.037116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0e97334bc1'
down_revision = '6f5638384dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ref_user_key', table_name='session')
    op.drop_constraint('session_ibfk_1', 'session', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('session_ibfk_1', 'session', 'user', ['ref_user_key'], ['user_key'])
    op.create_index('ref_user_key', 'session', ['ref_user_key'], unique=True)
    # ### end Alembic commands ###
