name: full stack

on: [pull_request]    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./docker/
    steps:
      - uses: actions/checkout@v2
      - name: build and run stack
        run: docker-compose up -d
        working-directory: ${{env.working-directory}}

